name: ci

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: setup-buildx-action@v3
      
      -
        name: Build and push
        uses: build-push-action@v5
        with:
          context: .
          push: true
          file: ./docker/Dockerfile
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest
